// Costanti per le azioni

export const CREATE_SURVEY_START = 'CREATE_SURVEY_START';
export const CREATE_SURVEY_SUCCESS = 'CREATE_SURVEY_SUCCESS';
export const UPDATE_SURVEY_START = 'UPDATE_SURVEY_START';
export const UPDATE_SURVEY_SUCCESS = 'UPDATE_SURVEY_SUCCESS';
export const CREATE_QUESTION = 'CREATE_QUESTION';

export const DELETE_SURVEY = 'DELETE_SURVEY';
export const DELETE_USER_SURVEYS_START = 'DELETE_USER_SURVEYS_START';
export const DELETE_USER_SURVEYS_SUCCESS = 'DELETE_USER_SURVEYS_SUCCESS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGOUT_USER_START = 'LOGOUT_USER_START';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const RESET_PASSWORD_START = 'RESET_PASSWORD_START';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const SURVEYLIST_FETCH_START = 'SURVEYLIST_FETCH_START';
export const SURVEYLIST_FETCH_SUCCESS = 'SURVEYLIST_FETCH_SUCCESS';

export const SHARED_SURVEYLIST_FETCH_START = 'SHARED_SURVEYLIST_FETCH_START';
export const SHARED_SURVEYLIST_FETCH_SUCCESS = 'SHARED_SURVEYLIST_FETCH_SUCCESS';
export const GET_PENDING_SURVEYS = 'GET_PENDING_SURVEYS';

export const ITEMS_FETCH_START = 'ITEMS_FETCH_START';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';

export const FRIENDS_FETCH_START = 'FRIENDS_FETCH_START';
export const FRIENDS_FETCH_SUCCESS = 'FRIENDS_FETCH_SUCCESS';
export const USER_SEARCH_START = 'USER_SEARCH_START';
export const USER_SEARCH_SUCCESS = 'USER_SEARCH_SUCCESS';
export const USER_SEARCH_FAIL = 'USER_SEARCH_FAIL';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const SENT_REQUEST = 'SENT_REQUEST';
export const GET_PENDING_REQUESTS = 'GET_PENDING_REQUESTS';

export const VOTING_START = 'VOTING_START';
export const VOTING_SUCCESS = 'VOTING_SUCCESS';
export const GET_AUTHOR_START = 'GET_AUTHOR_START';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_VOTE_START = 'GET_VOTE_START';
export const GET_VOTE_SUCCESS = 'GET_VOTE_SUCCESS';
export const GET_REACTIONS_START = 'GET_REACTIONS_START';
export const GET_REACTIONS_SUCCESS = 'GET_REACTIONS_SUCCESS';
export const SET_REACTION_START = 'SET_REACTION_START';
export const SET_REACTION_SUCCESS = 'SET_REACTION_SUCCESS';
export const HAS_TO_VOTE_START = 'HAS_TO_VOTE_START';
export const HAS_TO_VOTE_SUCCESS = 'HAS_TO_VOTE_SUCCESS';
export const QUESTIONS_FETCH_START = 'QUESTIONS_FETCH_START';
export const QUESTIONS_FETCH_SUCCESS = 'QUESTIONS_FETCH_SUCCESS';

export const SHARE_SURVEY_START = 'SHARE_SURVEY_START';
export const SHARE_SURVEY_SUCCESS = 'SHARE_SURVEY_SUCCESS';

export const GET_AVATARS_START = 'GET_AVATARS_START';
export const GET_AVATARS_SUCCESS = 'GET_AVATARS_SUCCESS';
export const SET_AVATAR_START = 'SET_AVATAR_START';
export const SET_AVATAR_SUCCESS = 'SET_AVATAR_SUCCESS';